INSERT INTO `conferences` (`id`, `name`, `english_name`, `alias_name`, `url_name`) VALUES
(1,	'PyCON Taiwan',	NULL,	NULL,	NULL),
(2,	'RubyConf Taiwan',	NULL,	NULL,	NULL),
(4,	'Java Developer Day',	NULL,	NULL,	NULL),
(5,	'JavaScript Developers Conference Taiwan',	'JSDC.tw',	'JSDC',	''),
(8,	'PHPConf Taiwan',	NULL,	NULL,	NULL),
(9,	'DrupalCamp Taipei',	NULL,	NULL,	NULL),
(10,	'WebConf Taiwan',	NULL,	NULL,	NULL),
(11,	'台灣駭客年會',	'Hacks In Taiwan Conference',	'HITCON',	''),
(12,	'台灣誘捕網路技術研討會',	'The Honeynet Project Taiwan Conference',	'HoneyCon',	NULL),
(13,	'Maker Faire : Taipei',	NULL,	NULL,	NULL),
(14,	'開源人年會',	'Conference for Open Source Coders, Users and Promoters',	'COSCUP',	''),
(15,	'Open Source Developers\' Conference',	NULL,	'OSDC',	''),
(16,	'學生計算機年會',	'Students\' Information Technology Conference ',	'SITCON',	''),
(17,	'行動科技應用開發者年會',	'Mobile / Open / Platform Conference',	'MOPCON',	'');
