INSERT INTO `conference_tags` (`conference_id`, `tag_name`) VALUES
(1,	'Programming'),
(1,	'Python'),
(2,	'Programming'),
(2,	'Ruby'),
(4,	'Programming'),
(4,	'Java'),
(5,	'Programming'),
(5,	'JavaScript'),
(8,	'Programming'),
(8,	'PHP'),
(9,	'Drupal'),
(10,	'Web'),
(11,	'Security'),
(12,	'Security'),
(13,	'Maker'),
(14,	'Web'),
(14,	'Mobile'),
(14,	'Open Data'),
(15,	'Programming'),
(16,	'Programming'),
(16,	'Game'),
(16,	'Web');
