INSERT INTO `conference_websites` (`conference_id`, `name`, `url`) VALUES
(1,	'PyCon',	'http://tw.pycon.org/'),
(2,	'RubyConf Taiwan',	'http://rubyconf.tw/'),
(1,	'Facebook',	'https://www.facebook.com/pycontw'),
(1,	'Google+',	'https://plus.google.com/101932655972746759016/posts'),
(1,	'Twitter',	'https://twitter.com/pycontw'),
(4,	'Java Developer Day',	'http://www.codedata.com.tw/event/javaday/2014/call-for-papers/'),
(5,	'JavaScript Developers Conference Taiwan',	'http://jsdc.tw/'),
(8,	'PHPConf Taiwan',	'http://phpconf.tw/'),
(9,	'DrupalCamp Taipei',	'http://2013.drupalcamp.tw/'),
(10,	'WebConf Taiwan',	'http://www.webconf.tw/'),
(10,	'Facebook',	'https://www.facebook.com/WebConfTaiwan'),
(10,	'Twitter',	'https://twitter.com/WebConfTaiwan'),
(11,	'台灣駭客年會 HITCON',	'http://hitcon.org/2013/'),
(11,	'Facebook',	'https://www.facebook.com/HITCON'),
(11,	'Google+',	'https://plus.google.com/109897934938045736272/posts'),
(12,	'台灣誘捕網路技術研討會',	'http://event.honeynet.org.tw/'),
(13,	'Maker Faire: Taipei',	'http://www.makerfaire.com.tw/'),
(14,	'COSCUP',	'http://coscup.org/'),
(14,	'Facebook Page',	'https://www.facebook.com/coscup'),
(14,	'YouTube',	'http://www.youtube.com/user/thecoscup'),
(14,	'Google+',	'https://plus.google.com/101434041225212178932'),
(14,	'Plurk',	'http://www.plurk.com/coscup'),
(14,	'Twitter',	'https://twitter.com/coscup'),
(14,	'Flickr',	'http://www.flickr.com/photos/coscup/'),
(15,	'OSDC',	'http://osdc.tw/'),
(16,	'學生計算機年會',	'http://sitcon.org/'),
(16,	'Facebook',	'https://www.facebook.com/groups/sitcon.tw/'),
(17,	'行動科技應用開發者年會',	'http://mopcon.org/'),
(17,	'Facebook',	'http://www.facebook.com/mopcon'),
(17,	'Google+',	'https://plus.google.com/116768206884057057248');
