INSERT INTO `groups` (`id`, `name`, `english_name`, `alias_name`, `url_name`) VALUES
(1,	'酷！學園',	'Study Area',	'SA',	''),
(2,	'Debian 中文社團',	NULL,	NULL,	'debian.tw'),
(3,	'Ubuntu 正體中文站',	NULL,	NULL,	NULL),
(4,	'Ubuntu 正體中文社團',	NULL,	NULL,	NULL),
(5,	'Ubuntu-TW 在地推廣組',	NULL,	NULL,	NULL),
(6,	'Arch Linux 中文',	NULL,	NULL,	NULL),
(7,	'openSUSE 正體中文社團',	NULL,	NULL,	NULL),
(8,	'LINUX MINT 中文社團',	NULL,	NULL,	NULL),
(9,	'Fedora 中文社團',	NULL,	NULL,	NULL),
(10,	'Taipei.py',	NULL,	NULL,	NULL),
(11,	'Python Hsinchu User Group',	'PyHUG',	'PyHUG',	''),
(12,	'Python Tainan User Group',	'Tainan.py',	NULL,	NULL),
(13,	'Python Taiwan',	NULL,	NULL,	NULL),
(14,	'PyLadies Taiwan',	NULL,	NULL,	NULL),
(15,	'Ruby Taiwan',	NULL,	NULL,	NULL),
(16,	'Ruby on Rails 讀書會',	NULL,	NULL,	NULL),
(17,	'Rails Girls Taiwan',	NULL,	NULL,	NULL),
(18,	'Rails meetup @Tainan ',	NULL,	NULL,	NULL),
(19,	'Kaohsiung Rails Meetup',	NULL,	NULL,	NULL),
(20,	'Perl台灣',	NULL,	NULL,	NULL),
(21,	'JavaScript.tw',	NULL,	'JSTW',	NULL),
(22,	'Taipei Javascript Enthusiasts',	NULL,	NULL,	NULL),
(23,	'jQuery 台灣',	NULL,	NULL,	NULL),
(24,	'node.js台灣',	'Node.js Taiwan',	NULL,	NULL),
(25,	'AngularJS.tw',	NULL,	NULL,	NULL),
(26,	'Ext JS 正體中文站',	NULL,	NULL,	NULL),
(27,	'PHP 台灣',	NULL,	NULL,	NULL),
(28,	'PHP 也有 Day',	NULL,	NULL,	NULL),
(29,	'Taiwan R User Group',	NULL,	NULL,	NULL),
(30,	'Qt Taiwan',	NULL,	NULL,	NULL),
(31,	'Android 台灣開發者社群',	'Android-Dev Taiwan',	'ADT',	NULL),
(32,	'Samsung Developer Community Taiwan',	NULL,	NULL,	NULL),
(33,	'iOS Dev Club',	NULL,	NULL,	NULL),
(34,	'CocoaHeads Taiwan',	NULL,	NULL,	NULL),
(35,	'CocoaHeads Taipei',	NULL,	NULL,	NULL),
(36,	'CocoaHeads Kaohsiung',	NULL,	NULL,	NULL),
(37,	'Golang 台灣社群',	'Golang Taipei Gathering',	'GTG',	''),
(38,	'Functional Thursday',	NULL,	NULL,	NULL),
(39,	'Processing.Taipei',	NULL,	NULL,	NULL),
(40,	'Puredata.Taipei',	NULL,	NULL,	NULL),
(41,	'台灣 Blender 使用者小聚',	'Taiwan Blender User Group',	NULL,	NULL),
(42,	'Taipei WordPress Meetup',	NULL,	NULL,	NULL),
(43,	'Drupal Taiwan',	NULL,	NULL,	NULL),
(44,	'KDE Taiwan',	NULL,	NULL,	NULL),
(45,	'OOo台灣社群',	NULL,	NULL,	NULL),
(46,	'Apache OpenOffice 台灣社群',	NULL,	NULL,	NULL),
(47,	'LibreOffice 正體中文使用者社團',	NULL,	NULL,	NULL),
(48,	'Openframeworks Notebook',	NULL,	NULL,	NULL),
(49,	'企鵝龍',	'Diskless Remote Boot in Linux',	'DRBL',	NULL),
(50,	'HTML5 與 CSS3 在台灣',	'HTML5&CSS3 IN TAIWAN',	NULL,	NULL),
(51,	'RGBA 網路設計師聚會',	NULL,	NULL,	NULL),
(52,	'Front-End Developers Taiwan',	NULL,	NULL,	NULL),
(53,	'高雄前端社群',	'Kaohsiung Front-End Community',	NULL,	NULL),
(54,	'HappyDesigner 快樂設計師',	NULL,	NULL,	NULL),
(55,	'Belp',	'Businiess, Entrepreneurship, Legal, Programming / Professional',	NULL,	NULL),
(56,	'自由開源軟體法律授權及產業動態新聞群組',	'FOSS licensing & Inudustry News Group',	NULL,	NULL),
(57,	'chrO.ot',	NULL,	NULL,	NULL),
(58,	'台灣雲端運算社群',	'Taiwan Cloud Computing User Group',	'CloudTW',	NULL),
(59,	'Taiwan Hadoop User Group',	NULL,	NULL,	NULL),
(60,	'AWS User Group in Taiwan',	'AWSUG in Taiwan',	NULL,	NULL),
(61,	'星系統社群',	'JuluOSDev',	NULL,	''),
(62,	'Code for Tomorrow',	NULL,	NULL,	NULL),
(63,	'Code for Kaohsiung',	NULL,	NULL,	NULL),
(64,	'零時政府',	'g0v',	'',	'g0v.tw'),
(65,	'Openlab.Taipei',	NULL,	NULL,	NULL),
(66,	'Fablab Taipei',	NULL,	NULL,	NULL),
(67,	'FabCafe Taipei',	NULL,	NULL,	NULL),
(68,	'Fablab Tainan',	NULL,	NULL,	NULL),
(69,	'MakerBar Taipei',	NULL,	NULL,	NULL),
(70,	'Fablab Dynamic',	NULL,	NULL,	NULL),
(71,	'Dimension+',	NULL,	NULL,	NULL),
(72,	'Taipei Hackerspace',	NULL,	NULL,	NULL),
(73,	'Arduino.Taipei',	NULL,	NULL,	NULL),
(74,	'Reprap.Taipei',	NULL,	NULL,	NULL),
(75,	'Taiwan 3D Printing',	NULL,	NULL,	NULL),
(76,	'Raspberry Pi社群',	NULL,	NULL,	NULL),
(77,	'DIY CNC Machine.Taipei',	NULL,	NULL,	NULL),
(78,	'RoboSmart.Taipei',	NULL,	NULL,	NULL),
(79,	'自由軟體鑄造場',	'Open Source Software Foundry ',	'OSSF',	''),
(80,	'台北開放原始碼軟體使用者社群',	'Taipei Open Source Software User Group ',	'TOSSUG',	''),
(81,	'嘿嘿星期四',	'Hacking Thursday',	'H4',	''),
(82,	'新竹碼農聚會',	'Hsinchu Coding Serfs Meeting',	NULL,	NULL),
(83,	'台中自由軟體愛好者聚會',	'Taichung Foss Fans Meeting',	'TCFFM',	''),
(84,	'中台灣 Linux 使用者聚會 ',	'Central Taiwan Linux User Group ',	'CTLUG',	''),
(85,	'大高雄Linux使用者協會',	'Kaohsiung Linux User Group ',	'KaLUG',	''),
(86,	'高雄軟體開發者社群',	'Kaohsiung Software Developer Group ',	'KSDG',	''),
(87,	'Meet Open Source Users in Tainan',	NULL,	'MOSUT',	''),
(88,	'OpenHack Taipei',	NULL,	NULL,	NULL),
(89,	'Mozilla 台灣社群',	'Mozilla Taiwan Community',	'Moztw',	''),
(90,	'台灣女子自由軟體工作小組',	'Women in Free and Open Source Software in Taiwan',	'WoFOSS',	''),
(91,	'開放原始碼新聞網',	'Open source software news in Taiwan',	NULL,	NULL),
(92,	'台灣維基人臺北定期聚會',	NULL,	'WPTP',	''),
(93,	'維基百科台灣社群台中聚會',	NULL,	'WPTC',	''),
(94,	'OpenStreetMap 台灣',	NULL,	NULL,	NULL),
(95,	'程式人雜誌',	NULL,	NULL,	NULL),
(96,	'Google Technology User Group',	'',	'GTUG Taipei',	NULL),
(97,	'ezgo',	NULL,	NULL,	NULL),
(98,	'國際遊戲開發者協會',	'International Game Developers Association',	'IGDA Taiwan',	''),
(99,	'獨立遊戲開發者分享會',	'',	'IGDSHARE',	''),
(100,	'Taiwan Java User Group',	'',	'TWJUG',	''),
(101,	'花蓮.py',	NULL,	NULL,	NULL),
(102,	'I Love Joomla!',	NULL,	NULL,	NULL),
(103,	'The Honeynet Project 台灣分會',	'The Honeynet Project Taiwan Chapter',	'',	NULL),
(104,	'臺灣維基人新竹聚會',	NULL,	'WPHC',	NULL),
(105,	'台灣維基社群',	'Taiwan Wikipedia Community',	NULL,	NULL),
(106,	'高雄獨立遊戲開發者聚會',	'Kaohsiung Indies Meet Up',	'KIMU',	NULL),
(107,	'台灣遊戲App開發者社群',	'Taiwan Game App Developer Community',	'TGADC',	NULL),
(108,	'台灣App開發者社群',	NULL,	'AppDC',	NULL),
(109,	'Android Taipei',	NULL,	NULL,	NULL),
(110,	'Ruby on Rails 新手村',	NULL,	NULL,	NULL),
(111,	'社團法人台灣互動設計協會',	'Interaction Design Association',	'IxDA Taiwan',	NULL),
(112,	'Laravel 台灣',	NULL,	NULL,	NULL);
